### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BerkieB** [MobScripting/BoneFive#1]
When I start this resource, I crash and no one can join the server anymore besides if I disable the resource again.
I'm using Es_Extended.
But I'm not using mythic hospital, would that be a problem?

**Comment by Dkamps18** [comment]
In Client/main.lua change line 53-60 to this
```
Citizen.CreateThread(
    function()
        while true do
            SetPlayerHealthRechargeMultiplier(PlayerId(0), 0.0)
	    Citizen.Wait(0)
        end
    end
)
```
